version: "2"

services:
  app:
    container_name: app
    restart: on-failure
    build:
      context: "./"
      dockerfile: Dockerfile
    links: 
      - redis
    environment:
      - TOR_PROXY=torproxy
      - REDIS_URL=redis://cache
    ports:
      - "8080:8080"
    depends_on: 
      - redis
      - torproxy

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  torproxy:
    container_name: torproxy
    image: dperson/torproxy

  ngrok:
    container_name: ngrok
    image: shkoliar/ngrok:latest
    ports:
      - 4551:4551
    links:
      - app
    environment:
      - DOMAIN=app
      - PORT=8080