version: "2.2"

services:
  client:
    container_name: client
    restart: on-failure
    build:
      context: "./client"
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - server

  server:
    container_name: server
    restart: on-failure
    build:
      context: "./server"
      dockerfile: Dockerfile
    links: 
      - redis
    environment:
      - TOR_PROXY=torproxy
      - REDIS_URL=redis://cache
    ports:
      - "8080:8080"
    depends_on: 
      - redis
  
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  torproxy:
    container_name: torproxy
    image: dperson/torproxy

