version: "2.2"

services:
  client:
    restart: on-failure
    build:
      context: "./client"
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - server

  server:
    restart: on-failure
    build:
      context: "./server"
      dockerfile: Dockerfile
    links: 
    environment: 
     - REDIS_URL=redis://cache
    ports:
      - "8080:8080"
  
  redis:
  image: redis
  container_name: cache
  expose:
    - 6379

  torproxy:
    image: dperson/torproxy

